"""Client utilities for connecting to APIGateway."""

from atlas.config.paths import get_data_dir

def get_gateway_headers() -> dict[str, str]:
    """Retrieve the ephemeral JWT token generated by APIGateway startup."""
    try:
        token_path = get_data_dir() / ".gateway_token"
        if token_path.exists():
            return {"Authorization": token_path.read_text().strip()}
    except Exception:
        pass
    return {}
